title: Yidong Ming's Homepage
page-top-title: Yidong MING
top-section-bg-text: The gloomist night will wear on to a morning!
home-subtitle: Yidong MING&ensp;|&ensp;明义栋
copyright-text: '&copy; Yidong MING 2024/10/12. All Rights Reserved.'
